import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmod, lstat, mkdir, mkdtemp, readFile, readdir, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { NativeProverAdapterError, parseManifest, parseStrictJson, runNativeProverAdapter } from './native-prover-adapter.mjs';
import { canonicalJson, deriveInstanceId, deriveProfileId } from '../core/verifier-profile.mjs';

const digest = (text) => createHash('sha256').update(text).digest('hex');
const hash = 'a'.repeat(64);
const valid = () => ({ schema: 'shield.cash/native-prover-adapter/v1', nativeProver: { backend: 'rapidsnark', path: '/native/prover', sha256: hash }, snarkjs: { path: '/native/snarkjs.cjs', sha256: hash, version: '0.7.6' }, profile: { bundleDirectory: '/native/profile', expected: { network: 'chipnet', profileId: `sha256:${hash}`, instanceId: `sha256:${'b'.repeat(64)}` } }, actions: ['deposit', 'transfer', 'withdrawal'].map((kind) => ({ kind, witness: { path: `/native/${kind}.wtns`, sha256: hash }, expectedPublicSignals: ['1', '2'] })), repetitions: 1, outputDirectory: '/tmp/native-prover-output' });

const executable = async (path, source) => { await writeFile(path, source, { mode: 0o700 }); await chmod(path, 0o700); };
const record = async (path) => ({ path, sha256: digest(await readFile(path)) });
const noStaging = async (root) => assert.deepEqual((await readdir(root)).filter((name) => name.includes('.staging-')), []);
// Structural profile fixture only: fake prover tests below never claim a proof is valid.
const profileFixture = async (root, zkey, vk) => {
  const profile = join(root, 'profile'); const artifactRoot = join(profile, 'artifacts'); await mkdir(artifactRoot, { recursive: true });
  const files = { 'relation.json': 'relation', 'constraints.r1cs': 'constraints', 'public-input-abi.json': 'abi', 'vk.json': await readFile(vk), 'final.zkey': await readFile(zkey), 'witness.wasm': 'wasm', 'verifier-set.json': 'set' };
  for (const [name, bytes] of Object.entries(files)) await writeFile(join(artifactRoot, name), bytes);
  const pin = (id, kind, name) => ({ id, kind, path: `artifacts/${name}`, sha256: `sha256:${digest(files[name])}` });
  const manifest = { schema: 'shield.cash/verifier-profile-manifest/v1', standard: { id: 'shield.cash', version: '1' }, profile: { proofSystem: 'groth16', curve: 'bn254', relation: { id: 'shielded-action-v2', sha256: `sha256:${digest(files['relation.json'])}` }, constraintSystemHash: `sha256:${digest(files['constraints.r1cs'])}`, publicInputAbi: { id: 'shielded-action-public-input-v1', sha256: `sha256:${digest(files['public-input-abi.json'])}` }, bchVerifierSetHash: `sha256:${digest(files['verifier-set.json'])}` }, setup: { mode: 'development-only', provenance: { method: 'local-initialization', initializerCommitment: `sha256:${digest('initializer')}` }, material: { phase1: { ptauSource: 'test-only', ptauSha256: `sha256:${digest('ptau')}` }, phase2: { initializationCommand: { argv: ['test'] }, contributionCommand: { argv: ['test'] }, randomnessCommitment: `sha256:${digest('randomness')}`, finalZkeySha256: `sha256:${digest(files['final.zkey'])}` } }, transcript: { status: 'not-applicable' }, contributions: [] }, toolchain: { compiler: { name: 'test', version: '0', sha256: `sha256:${digest('compiler')}` }, generator: { name: 'test', version: '0', sha256: `sha256:${digest('generator')}` } }, network: { name: 'chipnet' }, artifacts: [pin('bch-verifier-set', 'bch-verifier-set', 'verifier-set.json'), pin('constraint-system', 'constraint-system', 'constraints.r1cs'), pin('proving-key', 'proving-key', 'final.zkey'), pin('public-input-abi', 'public-input-abi', 'public-input-abi.json'), pin('relation-definition', 'relation-definition', 'relation.json'), pin('verification-key', 'verification-key', 'vk.json'), pin('witness-generator', 'witness-generator', 'witness.wasm')], identity: { profileId: '' }, genesis: { profileId: '', instanceId: '', network: 'chipnet', categoryInputOutpoint: { txid: '1'.repeat(64), vout: '0' }, stateNftCategory: '1'.repeat(64), reserveCapSatoshis: '10000000' } };
  manifest.identity.profileId = deriveProfileId(manifest); manifest.genesis.profileId = manifest.identity.profileId; manifest.genesis.instanceId = deriveInstanceId(manifest.genesis); await writeFile(join(profile, 'manifest.json'), canonicalJson(manifest));
  return { bundleDirectory: profile, expected: { network: 'chipnet', profileId: manifest.identity.profileId, instanceId: manifest.genesis.instanceId } };
};
const fixture = async (t, { publicSignals = '["1","2"]', mutate = '' } = {}) => {
  const root = await mkdtemp(join(tmpdir(), 'shield-native-prover-test-')); t.after(async () => rm(root, { recursive: true, force: true }));
  const native = join(root, 'prover.mjs'); const snarkjs = join(root, 'snarkjs.mjs'); const zkey = join(root, 'final.zkey'); const vk = join(root, 'vk.json');
  await writeFile(zkey, 'zkey'); await writeFile(vk, '{}');
  await executable(native, `#!/usr/bin/env node\nimport { writeFileSync, appendFileSync } from 'node:fs';\nconst args = process.argv.slice(2); ${mutate === 'prover' ? "appendFileSync(process.argv[1], '\\n// changed');" : ''}\nwriteFileSync(args[2], '{}'); writeFileSync(args[3], ${JSON.stringify(publicSignals)});\n`);
  await executable(snarkjs, `#!/usr/bin/env node\n${mutate === 'snarkjs' ? "import { appendFileSync } from 'node:fs';" : ''}\nconst args = process.argv.slice(2); if (args[0] === '--version') { console.log('snarkjs@0.7.6'); process.exit(99); } ${mutate === 'snarkjs' ? "appendFileSync(process.argv[1], '\\n// changed');" : ''}\nprocess.exit(0);\n`);
  const actions = [];
  for (const kind of ['deposit', 'transfer', 'withdrawal']) { const witness = join(root, `${kind}.wtns`); await writeFile(witness, kind); actions.push({ kind, witness: await record(witness), expectedPublicSignals: ['1', '2'] }); }
  const manifest = { schema: 'shield.cash/native-prover-adapter/v1', nativeProver: { backend: 'rapidsnark', ...await record(native) }, snarkjs: { ...await record(snarkjs), version: '0.7.6' }, profile: await profileFixture(root, zkey, vk), actions, repetitions: 1, outputDirectory: join(root, 'published') };
  const manifestPath = join(root, 'manifest.json'); const save = async () => writeFile(manifestPath, `${JSON.stringify(manifest)}\n`); await save(); return { root, native, snarkjs, zkey, manifest, manifestPath, save };
};

test('accepts exactly the three action kinds and pinned records', () => assert.equal(parseManifest(valid()).repetitions, 1));
test('rejects unknown or duplicate action kinds', () => { const input = valid(); input.actions[2].kind = 'deposit'; assert.throws(() => parseManifest(input), NativeProverAdapterError); });
test('rejects relative manifest file paths and output directories before resolution', () => { const input = valid(); input.nativeProver.path = 'relative/prover'; assert.throws(() => parseManifest(input), /absolute path/); input.nativeProver.path = '/native/prover'; input.outputDirectory = 'relative/output'; assert.throws(() => parseManifest(input), /outputDirectory must be an absolute path/); });
test('rejects malformed backend/hashes, unbounded repetitions, extra signals, and non-canonical scalars', () => { const input = valid(); input.nativeProver.backend = 'other'; assert.throws(() => parseManifest(input), /backend must be rapidsnark/); input.nativeProver.backend = 'rapidsnark'; input.nativeProver.sha256 = 'z'; assert.throws(() => parseManifest(input), NativeProverAdapterError); input.nativeProver.sha256 = hash; input.repetitions = 21; assert.throws(() => parseManifest(input), NativeProverAdapterError); input.repetitions = 20; assert.equal(parseManifest(input).repetitions, 20); input.repetitions = 1; input.actions[0].expectedPublicSignals = ['1', '2', '3']; assert.throws(() => parseManifest(input), NativeProverAdapterError); input.actions[0].expectedPublicSignals = ['01', '2']; assert.throws(() => parseManifest(input), NativeProverAdapterError); input.actions[0].expectedPublicSignals = ['21888242871839275222246405745257275088548364400416034343698204186575808495617', '2']; assert.throws(() => parseManifest(input), NativeProverAdapterError); });
test('strict parser rejects duplicate keys at every object scope and preserves escaped strings', () => { assert.throws(() => parseStrictJson('{"a":1,"a":2}', 'manifest'), NativeProverAdapterError); assert.throws(() => parseStrictJson('{"a":{"b":1,"b":2}}', 'manifest'), NativeProverAdapterError); assert.equal(parseStrictJson(JSON.stringify({ a: 'x\\"y' }), 'manifest').a, 'x\\"y'); });
test('rejects duplicate manifest keys before execution', async (t) => { const f = await fixture(t); const text = await readFile(f.manifestPath, 'utf8'); await writeFile(f.manifestPath, text.replace('{', '{"schema":"shield.cash/native-prover-adapter/v1",')); await assert.rejects(runNativeProverAdapter(f.manifestPath), NativeProverAdapterError); });
test('rejects a non-UTF-8 manifest before execution', async (t) => { const f = await fixture(t); await writeFile(f.manifestPath, Buffer.from([0x7b, 0xff, 0x7d])); await assert.rejects(runNativeProverAdapter(f.manifestPath), /not valid UTF-8/); });
test('rejects witness path hash drift before native execution', async (t) => { const f = await fixture(t); await writeFile(f.manifest.actions[0].witness.path, 'tampered'); await assert.rejects(runNativeProverAdapter(f.manifestPath), /SHA-256 mismatch/); await assert.rejects(lstat(f.manifest.outputDirectory)); });
test('rejects a symlinked canonical profile artifact even when its target hash matches', async (t) => { const f = await fixture(t); const target = join(f.root, 'zkey-target'); await writeFile(target, 'zkey'); const profileZkey = join(f.manifest.profile.bundleDirectory, 'artifacts', 'final.zkey'); await rm(profileZkey); await symlink(target, profileZkey); await assert.rejects(runNativeProverAdapter(f.manifestPath), /bundle is invalid: artifact must be a regular non-symlink/); });
test('rejects a symlink output parent', async (t) => { const f = await fixture(t); const target = join(f.root, 'real-parent'); const link = join(f.root, 'linked-parent'); await mkdir(target); await symlink(target, link); f.manifest.outputDirectory = join(link, 'published'); await f.save(); await assert.rejects(runNativeProverAdapter(f.manifestPath), /output parent must be a direct non-symlink directory/); });
test('detects a self-mutating native prover and cleans staging', async (t) => { const f = await fixture(t, { mutate: 'prover' }); await assert.rejects(runNativeProverAdapter(f.manifestPath), /nativeProver (identity|content) changed/); await noStaging(f.root); });
test('detects a self-mutating verifier tool and cleans staging', async (t) => { const f = await fixture(t, { mutate: 'snarkjs' }); await assert.rejects(runNativeProverAdapter(f.manifestPath), /snarkjs (identity|content) changed/); await noStaging(f.root); });
test('rejects malformed or extra native public signals and cleans staging', async (t) => { const f = await fixture(t, { publicSignals: '["1","2","3"]' }); await assert.rejects(runNativeProverAdapter(f.manifestPath), /exactly two public signals/); await noStaging(f.root); });
test('does not overwrite an existing output destination', async (t) => { const f = await fixture(t); await writeFile(f.manifest.outputDirectory, 'occupied'); await assert.rejects(runNativeProverAdapter(f.manifestPath), /already exists/); assert.equal(await readFile(f.manifest.outputDirectory, 'utf8'), 'occupied'); await noStaging(f.root); });
test('does not remove a pre-existing staging directory when mkdir collides', async (t) => { const f = await fixture(t); const staging = join(f.root, '.published.staging-collision'); await mkdir(staging); await writeFile(join(staging, 'sentinel'), 'preserve'); await assert.rejects(runNativeProverAdapter(f.manifestPath, { stagingId: 'collision' }), /native prover adapter failed/); assert.equal(await readFile(join(staging, 'sentinel'), 'utf8'), 'preserve'); });
test('runs a pinned happy path and publishes an atomically staged result', async (t) => { const f = await fixture(t); const result = await runNativeProverAdapter(f.manifestPath); assert.equal(result.actions.length, 3); assert.equal((await readFile(join(f.manifest.outputDirectory, 'result.json'), 'utf8')).includes('native-prover-adapter-result/v1'), true); assert.match(result.nativeProver.ino, /^\d+$/); assert.equal(result.nativeProver.backend, 'rapidsnark'); assert.equal(result.actions[0].runs[0].proving.memory.method, 'linux-proc-status-vmrss-process-tree-sampled'); assert.ok(result.actions[0].runs[0].proving.memory.peakProcesses >= 1); await noStaging(f.root); });
