/**
 * Shared CLI error codes — fail-closed JSON envelopes.
 */

export const ERROR_CODES = Object.freeze({
  // parse / grammar
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
  OPTION_VALUE_REQUIRED: 'OPTION_VALUE_REQUIRED',
  USAGE: 'USAGE',
  // identity / home
  HOME_NOT_FOUND: 'HOME_NOT_FOUND',
  HOME_PROFILE_MISMATCH: 'HOME_PROFILE_MISMATCH',
  HOME_DESIGN_MISMATCH: 'HOME_DESIGN_MISMATCH',
  HOME_NETWORK_MISMATCH: 'HOME_NETWORK_MISMATCH',
  HOME_BACKEND_MISMATCH: 'HOME_BACKEND_MISMATCH',
  UNKNOWN_ALIAS: 'UNKNOWN_ALIAS',
  PROFILE_NOT_REGISTERED: 'PROFILE_NOT_REGISTERED',
  TIP_NOT_IDENTITY: 'TIP_NOT_IDENTITY',
  // lifecycle
  DURABILITY_REQUIRED: 'DURABILITY_REQUIRED',
  SEND_ALREADY_ATTEMPTED: 'SEND_ALREADY_ATTEMPTED',
  AUTOMATIC_REBROADCAST_FORBIDDEN: 'AUTOMATIC_REBROADCAST_FORBIDDEN',
  REBROADCAST_ACK_REQUIRED: 'REBROADCAST_ACK_REQUIRED',
  REBROADCAST_BYTES_REQUIRED: 'REBROADCAST_BYTES_REQUIRED',
  REBROADCAST_CAS_REQUIRED: 'REBROADCAST_CAS_REQUIRED',
  SEND_INDETERMINATE: 'SEND_INDETERMINATE',
  REJECTED: 'REJECTED',
  LOCK_HELD: 'LOCK_HELD',
  // capabilities
  CAPABILITY_BLOCKED: 'CAPABILITY_BLOCKED',
  CAPABILITY_UNSUPPORTED: 'CAPABILITY_UNSUPPORTED',
  LAB_ACK_REQUIRED: 'LAB_ACK_REQUIRED',
  // migration
  MIGRATION_REQUIRED: 'MIGRATION_REQUIRED',
  LEGACY_DATA_HOME_NOT_AUTO: 'LEGACY_DATA_HOME_NOT_AUTO',
  // maintainer / ambient
  MAINTAINER_PATH_FORBIDDEN: 'MAINTAINER_PATH_FORBIDDEN',
  AMBIENT_CONFIG_FORBIDDEN: 'AMBIENT_CONFIG_FORBIDDEN',
  // demo
  DEMO_READ_ONLY: 'DEMO_READ_ONLY',
  // general
  INTERNAL: 'INTERNAL',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
});

export class CliError extends Error {
  constructor(code, message, { exitCode = 2, details = null } = {}) {
    super(message);
    this.name = 'CliError';
    this.code = code;
    this.exitCode = exitCode;
    this.details = details;
  }
}

export function cliFail(code, message, options) {
  throw new CliError(code, message, options);
}
